### ISSUE TITLE
Roadmap Plan

### ISSUE THREAD

**Issue by aladinoster** [licit-lab/symupy#51]
# About 

This issue is declared to settle a set of activities and provide a general status on how the current package is behaving. The aim is to establish specific activities to include after the `0.5.0` version and enable richer documentation as well as useful guidance to the general public. This issue will work as a master plan for the development of the activities 

*Policy development update*:  

## General activities and remarks 

- [ ] Create tutorials for possible cases → #19 
- [x] Code architecture / Integrate `Smymutools` inside `symupy` → #61, #67 
- [x] Update and provide contribution guidelines
- [x] Define a list of traffic objects and corresponding functionalities 
- [x] List and define set of current objects and their interactions
- [x] New code architecture → #61 
----

#### Symudev
- [x] Create conda recipe `symudev` → [3e3416a](https://github.com/licit-lab/symudev/commit/3e3416a95b74a29d40e1d165bb4783468a911920#diff-d0edee15f91b406f3f99726e44eb990be6e34fd0345b52b910c568e0eef6a2a8) 
- [x] Add CI for conda build  → https://github.com/licit-lab/symudev/commit/094e366c37279f1ba54a9a928d1a425b879dcab6
- [x] Publish package on channel `licit-lab` 
    - [x] OX 
    - [x] Linux
    - [ ] Windows → https://github.com/licit-lab/symudev/issues/25

#### Symupy
- [x] Create conda recipe `symupy` → #46
- [x] Add CI for conda build → 90a9b187b6580b0c942e5056ac4618c510f2899d
- [x] Publish package on channel `licit-lab` 
    - [x] OX 
    - [x] Linux
    - [ ] Windows → https://github.com/licit-lab/symudev/issues/25

### Distribution 
 
- [x] Publish package to `licit-lab` in anaconda

### Containerization 

- [x] Create `Dockerfile` 
- [x] Build image 
- [ ] Publish image
- [x] Add CI/actions to push image when updates. → #55 

---

### Utils 

- [x] Parsing XML  
    - [ ] Load data in memory (efficently)

### Preprocessing 

 - [x] Parse XML <-> Transform  into (Traffic System Objects)
 - [ ] Tutorial Traffic Objects
      - Simple network for demonstrator purposes (Load file/ Explore objects)
      - Statistics (Scenario) 
 - [ ] XML Templates Generator.
 - [ ] #92
 - [ ] Network Generator (From OSM, 3rd party sources)
 - [ ] Data Visualization (Network, Sensors, Zones, Demand Scenario)

### Runtime 

 - [x] Simulation Monitoring (Indicators, Logger (Time/Messages))
 - [ ] Asynchronous Information Retreival/Actuation (Event Handler)
 - [ ] #93

### Postprocessing 

 - [ ] Parse XML <->  Transform (DataFrames, csv, database) 
 - [ ] #90
 - [ ] #91

**Comment by aladinoster** [comment]
# About 

This issue is declared to settle a set of activities and provide a general status on how the current package is behaving. The aim is to establish specific activities to include after the `0.5.0` version and enable richer documentation as well as useful guidance to the general public. This issue will work as a master plan for the development of the activities 

*Policy development update*:  

## General activities and remarks 

- [ ] Create tutorials for possible cases
- [ ] Integrate `Smymutools` inside `symupy`
- [x] Update and provide contribution guidelines
- [ ] Define a list of traffic objects and corresponding functionalities 
- [ ] List and define set of current objects and their interactions

## New features  

- [ ] Plot trajectory data from an XML output file.
- [ ] Plot demand data from an XML input file
- [ ] Plot sensor data from an XML output file
- [ ] Transform XML data into a database like file 
- [ ] Tool to visualize animated simulations in jupyter

**Comment by aladinoster** [comment]
This plan is outdated. Independent issues have been opened in specific topics.
